### PR TITLE
Add simple demo

### LINKED ISSUE #77: Deploy streamlit demo
Deploy the streamlit app following the instructions [here](https://docs.streamlit.io/en/stable/deploy_streamlit_app.html). Currently waiting to be granted access to Streamlit for Teams.

### PR DESCRIPTION
**Pull request by JohnGiorgi**
This PR adds a simple demo built with Streamlit (thanks @maxkfranz for the suggestion). The user can specify a query PMID (and optionally some other PMIDs to search against) and the top k most similar results will be displayed. See below for a screenshot.

~~The demo is not hosted yet, for that I have to wait until I get access to [Streamlit for Teams](https://streamlit.io/for-teams) (tracking this in #77)~~ @maxkfranz has hosted it

image

Closes #77.

### CODE REVIEW

**Review by maxkfranz — APPROVED** [review]
Unless there are objections, let's merge this in.  I think I should be able to deploy it with my account.

**Comment by maxkfranz** [comment]
https://share.streamlit.io/pathwaycommons/semantic-search/add-simple-demo/semantic_search/demo.py

**Comment by JohnGiorgi** [comment]
Okay there was just one last thing I wanted to do and that was display the titles. I found that I can do it very quickly with the PubTator API. Will merge in a little...

**Comment by maxkfranz** [comment]
OK, one other nice-to-have may be to be able to paste in PubMed URLs into the text box.  That may be easier for testing rather than hand-editing to extract the ID.

**Comment by JohnGiorgi** [comment]
Good call! Okay you can now copy/paste URLs, and titles are show along with PMIDs/scores. I put a new screenshot in my original comment. This is ready to merge unless anyone has any outstanding requests!

**Comment by JohnGiorgi** [comment]
@maxkfranz Will the link change to:

https://share.streamlit.io/pathwaycommons/semantic-search/master/semantic_search/demo.py

Once this is merged? If so I will add a link at the top of the readme.

**Comment by maxkfranz** [comment]
> @maxkfranz Will the link change to:
> 
> https://share.streamlit.io/pathwaycommons/semantic-search/master/semantic_search/demo.py
> 
> Once this is merged? Thinking about adding a link at the top of the readme.

Yes, I'll post the new link once merged

**Comment by JohnGiorgi** [comment]
LGTM!

**Comment by maxkfranz** [comment]
Deployed: https://share.streamlit.io/pathwaycommons/semantic-search/semantic_search/demo.py

**Pull request merged**
