### PR TITLE
Fix bugs due to HF Transformers 4.0.0

### LINKED ISSUE #32: Error on search
I'm getting a 500 HTTP status trying to search when running locally. Oddly the docker container runs fine?

- Reproduce 
  - python 3.8.2 64-bit 
  - OSX 10.15.7 (19H2)

POST `http://localhost:9234/`

```json

{
    "query": "9887103",
    "documents":["9887103", "30049242", "22936248"],
    "top_k":3
}

```

Errors:

```bash
INFO:     127.0.0.1:59397 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".../opt/miniconda3/envs/myenv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
...
    raise TypeError(
TypeError: batch_text_or_text_pairs has to be a list (got <class 'tuple'>)
```

Response from Docker container:

```json
[
  {
    "uid": "9887103",
    "score": 1.0
  },
  {
    "uid": "30049242",
    "score": 0.7884007692337036
  },
  {
    "uid": "22936248",
    "score": 0.6746125221252441
  }
]
```

### PR DESCRIPTION
**Pull request by JohnGiorgi**
# Overview

The root cause of #32 was that the `query` was not formatted properly. Instead of:

```json
    {
        "query": "9887103",
        "documents": ["9887103", "30049242", "22936248"],
        "top_k": 3
    }
```

you need to provide valid JSON for the query and documents, like this

```json
    {
        "query": {"uid": "9887103"},
        "documents": [{"uid": "9887103"}, {"uid": "30049242"}, {"uid": "22936248"}],
        "top_k": 3
    }
```

Not sure why this query ever worked?

After I fixed this, I found several bugs due to `transformers>4.0.0`. I fixed them and pinned `transformers>=4.0.1,<4.1.0`.

## Other Changes

- ♻️ Combined the query and documents validators into one validator.
- ♻️ Use new Dataclass outputs from `transformers` to simplify `_encode`.

## Closes

Closes #32.

### CODE REVIEW

**Comment by jvwong** [comment]
> Not sure why this query ever worked?

That @validator on `Query` should work...let me try to save this so the api isn't breaking (for Factoid)...

**Comment by JohnGiorgi** [comment]
Ah, I see now. Okay if that is the case then all you need to do is pass `pre=True` to the old validators and it will work.

**Comment by jvwong** [comment]
No don't change anything, I can make a couple of lines

**Comment by JohnGiorgi** [comment]
Okay if you are sure. This code works:

```python
class Document(BaseModel):
    uid: UID
    text: str = None


class Query(BaseModel):
    query: Document
    documents: List[Document] = []
    top_k: Optional[int] = None

    @validator("query", pre=True)
    def normalize_document(cls, v):
        if isinstance(v, UID):
            docs = uids_to_docs([v])
            return Document(**docs[0])
        else:
            return v

    @validator("documents", pre=True)
    def normalize_documents(cls, v):
        if all(isinstance(x, UID) for x in v):
            return [Document(**k) for k in uids_to_docs(v)]
        else:
            return v
```

**Comment by jvwong** [comment]
Oh ok then put that in and I can test.

**Comment by JohnGiorgi** [comment]
@jvwong Try that. I tested locally and the query:

```json
{
        "query": "9887103",
        "documents": ["9887103", "30049242", "22936248"],
        "top_k": 3
}
```

works.

**Review by jvwong — APPROVED** [review]
Works for me!

**Pull request merged**
