### PR TITLE
Enable GPU processing

### PR DESCRIPTION
**Pull request by JohnGiorgi**
# Overview

This PR enables GPU processing. Just supply the CUDA device ID on a CUDA-enabled machine with a GPU on server startup:

```bash
CUDA_DEVICE=0 uvicorn main:app
```

I also made `max_length` configurable (it currently defaults to 512). The smaller this number the faster the model will be able to process the text, with the downside being that text longer than this length will be truncated. E.g.,

```
CUDA_DEVICE=0 MAX_LEN=384 uvicorn main:app
```

## TODOs

- [x] Run the code on a machine with a GPU and confirm the speedup is as expected.
- [x] Benchmark the speedup (over 10X, see https://github.com/PathwayCommons/semantic-search/pull/9#issuecomment-655067904)

## Other changes

- :zap: Encode query along with documents to be queried, saving 1 forward pass per `POST` request.
- :zap: Smart batching/padding based on sequence length.
- :wrench: Make mean pooling the default. This should lead to much better performance (in terms of ranking of documents, not the speed of processing).
- ♻️ Drop the `Index` object. We weren't using it as I expected so it was just overhead we don't need.
- :recycle: Create the `CosineSimilarity` object _once_ at startup, not once _per query_.
- :sparkles: Max `max_length` configurable.
- :wrench: Change default `batch_size` to 64. I found that this led to lowest time per query.

### CODE REVIEW

**Comment by JohnGiorgi** [comment]
@maxkfranz @jvwong I made two changes that should speed things up on CPU/GPU. 

Basically, 

- Batch text based on length (this minimizes "padding" and therefore the number of computations per doc)
- Only "pad" up to the longest document in a batch (not the model's max length). Again, this minimizes padding and # of computations per doc.

I expect this to have a pretty significant positive effect on runtime but it would be good to confirm.

**Comment by maxkfranz** [comment]
Sounds good.  Let me know if it would help for me to reset your machine in the lab (e.g. to set a fixed IP address).  Then we could use it to test the performance with the GPU.  It only takes a few minutes for me to walk over.

**Comment by JohnGiorgi** [comment]
Yeah, that would be great. Aiden already rebooted it for me but I still can't recconnect so something else might be up. I will aim to be at my computer here at home when you go in to see if we can quickly debug it in real-time

**Comment by risserlin** [comment]
Hi John, 
I was having issues connecting to machine as well.  Is your machine a mac? (my system update changed the way I could connect to my machine and I had to go in to figure out how to fix it).
you can also ask Jeff Liu to see if your machine is broadcasting correctly.  Mine was broadcasting but screen share was disabled.

**Comment by JohnGiorgi** [comment]
Yup the laptop I am trying to use to connect to my workstation is a Mac. What did you end up doing to fix the problem? I don't need screen share enabled, just need to ssh in.

**Comment by risserlin** [comment]
Hi John, 
The computer I was trying to connect to was a mac and I had to physically log in locally and turn on ssh access.  But it looks like your box is one of the Dell workstations (which I assume is running linux).  Might be a different issue.  What is the IP address of your machine?

**Comment by jvwong** [comment]
This is a file for querying ~1000 documents (p53-mdm2)
 
[data.json.zip](https://github.com/PathwayCommons/semantic-search/files/4870856/data.json.zip)

```sh
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/fastapi/applications.py", line 171, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/fastapi/routing.py", line 196, in app
    raw_response = await run_endpoint_function(
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/fastapi/routing.py", line 147, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 166, in query
    embeddings = encode(text)
  File "./main.py", line 137, in encode
    embedding = _encode(
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "./main.py", line 114, in _encode
    sequence_output, _ = model(**inputs)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/transformers/modeling_bert.py", line 752, in forward
    embedding_output = self.embeddings(
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/transformers/modeling_bert.py", line 179, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 112, in forward
    return F.embedding(
  File "/Users/jeffreywong/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

**Comment by maxkfranz** [comment]
> I guess I don't have a CUDA-enabled GPU. I was seeing some errors with larger queries using the CPU mode. I'll try to attach.
 
I don't think that CUDA (or any Nvidia cards) are supported on Mac anymore.  For good CUDA support, you should use a Linux machine.

**Comment by JohnGiorgi** [comment]
@risserlin My machine is one of the Dell workstations, it's IP is: 192.168.72.150

**Comment by risserlin** [comment]
@JohnGiorgi I logged in with user name baderlab with no problem.  Are you still having issues?

**Comment by risserlin** [comment]
@JohnGiorgi which VPN are you using?  Are you using the recommended free OpenVPN (I think it is called).  About a year ago I changed to viscosity (a paid program but it was maybe 20$ or something) and all my issues connecting went away.  With the OpenVPN I used to have to reboot my router to get it to work sometimes.

**Comment by JohnGiorgi** [comment]
@risserlin Weird. I am now able to login with `ssh john@192.168.72.150`. I called that exact same command a few times on different days after Aiden rebooted the machine (with my Donelly VPN on) and it never worked. Yes, I am using TunnelBlick, the app Jeff Liu told me to use (I think? Can't even remember it was a while ago).

Anyways, I can log in now so @maxkfranz you no longer need to go in for me. Thanks a lot for offering though.

**Comment by jvwong** [comment]
I am able to login. @JohnGiorgi do you want me to do anything?

**Comment by JohnGiorgi** [comment]
Nope all good @jvwong. I will try to benchmark the speed up with the GPU this afternoon.

**Comment by JohnGiorgi** [comment]
@jvwong @maxkfranz  Okay, so as expected a GPU makes a massive difference. Using the ~1000 examples from @jvwong, here are the results:

- `CUDA_DEVICE=-1 BATCH_SIZE=64 MAX_LENGTH=384 uvicorn main:app` --> 146.6 seconds
- `CUDA_DEVICE=0 BATCH_SIZE=64 MAX_LENGTH=384 uvicorn main:app` --> 14.4 seconds

So about 10X (!) faster.

I am still working on training a smaller model, which should drive that 14.4 seconds down even further.

**Comment by JohnGiorgi** [comment]
@jvwong Feel free to merge!

**Pull request merged**
